import pandas as pd
df=pd.read_csv(r"C:\python programs\DNA_projects\data\bio_dataset.csv")
print("Orignal Dataset:")
print(df)
print("\nMissing Values:")
print(df.isnull().sum())
df["Expression"]=df["Expression"].fillna(df["Expression"].mean())
df=df.drop_duplicates()
print("\nCleaned Dataset:")
print(df)
print("\nSummary Statistics")
print(df.describe())
print("\nDataset Information:")
print(df.info())